### ISSUE TITLE
Support for ThreeTen-Extra 

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/typehandlers-threeten-extra#1]
[ThreeTen-Extra](https://github.com/ThreeTen/threeten-extra) is a small library that builds on the Java SE 8 java.time package. It provides some additional classes that come in handy as value types. Hence; we will consider to provide type handlers for ThreeTen-Extra.

### Related Issues

* mybatis/typehandlers-jsr310#31

**Comment by harawata** [comment]
Hi @kazuki43zoo ,

This is about the pom.xml in mybatis-typehandlers-threeten-extra, right?
Then `compile` scope should be fine.
It probably is better to omit `<optional />` although it would not matter in most cases.

**Comment by kazuki43zoo** [comment]
Hi @harawata ,

Oh.. issue description is copy & paste from  mybatis/typehandlers-jsr310#31.
In current definition, it is `provided` scope. (See https://github.com/mybatis/typehandlers-threeten-extra/blob/master/pom.xml#L78-L83)

I think that `provided` scope is better in this case.
What do you think ?

**Comment by harawata** [comment]
`compile` seems more appropriate in this case, but it's up to you. :)

So, what is the goal of this issue?

**Comment by kazuki43zoo** [comment]
Goal of this issue provide type handlers for ThreeTen-Extra.
I think it is completed already.

**Comment by kazuki43zoo** [comment]
I've updated description.

**Comment by harawata** [comment]
OK. Let me know if you need me to do anything!

**Comment by kazuki43zoo** [comment]
@harawata 

> Let me know if you need me to do anything!

Thanks !! Please review gh-12.

**Comment by raupachz** [comment]
I would go with provided. Unlikely that you use this project if you have neither Threeten-Extra or MyBatis in your path. It is not really "optional".

Additionally maybe we can use Maven version ranges? I am not that familiar with them but I think it would fit this project. It is unlikely that Threeten-Extra changes or removes classes. More likely that they add a class or two.

If we use a provided scope with version range [1.0,) it gives developers to upgrade Threeten-Extra without waiting for this project to update. But like I said I am not familiar with version ranges and their impact.

**Comment by harawata** [comment]
> I would go with provided.

`provided` it is, then :)

> If we use a provided scope with version range [1.0,) it gives developers to upgrade Threeten-Extra without waiting for this project to update

In general, we should avoid using version range because it can break the build without any modification if threeten-extra released a backward-incompatible version in the future.

Besides, regardless of the scope we choose, developers can override the version specified in __mybatis-typehandlers-threeten-extra__'s pom.xml by adding the __threeten-extra__ dependency explicitly to their pom.xml (which is required anyway as we choose `provided` scope).

**Comment by kazuki43zoo** [comment]
@raupachz and @harawata, Thanks for your contribution and comments !!
I've closed this issue because all tasks are completed. If there are problem, please reopen this.

Thanks again.
